version: "3"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=grammarguardian-ar
      - POSTGRES_USER=manfred
      - POSTGRES_PASSWORD=SEGa1122
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
